export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:5000';

export const bloodCompatibility = {
  'O-': ['O-'],
  'O+': ['O-', 'O+'],
  'A-': ['A-', 'O-'],
  'A+': ['A-', 'O-', 'A+', 'O+'],
  'B-': ['B-', 'O-'],
  'B+': ['B-', 'O-', 'B+', 'O+'],
  'AB-': ['AB-', 'A-', 'B-', 'O-'],
  'AB+': ['AB-', 'A-', 'B-', 'O-', 'AB+', 'A+', 'B+', 'O+']
};

export const i18n = {
  en: {
    nav: ['Home', 'About', 'Find Donor', 'FAQ', 'Contact'],
    quickLinks: 'Quick Links',
    footerDesc: 'A platform dedicated to connecting kidney patients with compatible donors in Sri Lanka through a secure, ethical, and efficient matching system.',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    welcome: 'Welcome',
    appName: 'Kidney Connect Sri Lanka',
    homeHeroTitle: 'Connecting Kidney Patients with Compassionate Donors in Sri Lanka',
    homeHeroDescription: 'A secure platform where patients can find compatible kidney donors and individuals can register as potential donors to save lives.',
    findDonorBtn: 'Find a Donor',
    becomeDonorBtn: 'Become a Donor',
    langNotice: 'This platform is available in English, Sinhala, and Tamil. Select your preferred language above.',
    aboutTitle: 'About Kidney Connect Sri Lanka',
    missionTitle: 'Our Mission',
    missionText: 'Kidney Connect Sri Lanka was established to address the critical shortage of kidney donors in Sri Lanka. With over 1,200 patients waiting for transplants and an average wait time of 4-5 years, our mission is to create a secure, efficient platform that connects compatible donors with patients in need.',
    findDonorTitle: 'Find a Compatible Donor',
    loginRequiredTitle: 'Login Required',
    loginRequired: 'You need to be logged in to access the donor matching system.',
    loginNow: 'Login Now',
    searchCriteria: 'Search Criteria',
    patientBloodType: 'Patient Blood Type',
    preferredDonorLocation: 'Preferred Donor Location',
    anywhereSriLanka: 'Anywhere in Sri Lanka',
    donorAgeRange: 'Donor Age Range',
    medicalUrgency: 'Medical Urgency',
    highUrgency: 'High (Currently on dialysis)',
    mediumUrgency: 'Medium (Will need dialysis soon)',
    lowUrgency: 'Low (Early stage kidney disease)',
    searchDonors: 'Search for Donors',
    potentialMatches: 'Potential Donor Matches',
    matchesFoundPrefix: 'Based on your criteria, we found',
    matchesFoundSuffix: 'potential donor(s).',
    noMatches: 'No matches found',
    bloodType: 'Blood Type',
    age: 'Age',
    location: 'Location',
    status: 'Status',
    registerTitle: 'Create Your Account',
    registerDesc: 'Register as a patient or donor to join our community',
    registerAs: 'I want to register as:',
    patientLabel: 'Patient (Need a kidney)',
    donorLabel: 'Donor (Want to donate)',
    fullName: 'Full Name',
    nicNumber: 'NIC Number',
    emailAddress: 'Email Address',
    phoneNumber: 'Phone Number',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    selectGender: 'Select Gender',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    selectBloodType: 'Select Blood Type',
    selectProvince: 'Select Province',
    agreement: 'I agree to the terms and conditions and confirm that all information provided is accurate.',
    createAccount: 'Create Account',
    haveAccount: 'Already have an account?',
    loginHere: 'Login here',
    loginTitle: 'Login to Your Account',
    loginDesc: 'Access your patient or donor profile',
    emailOrNic: 'Email Address or NIC',
    noAccount: "Don't have an account?",
    registerHere: 'Register here',
    faqTitle: 'Frequently Asked Questions',
    faq1Q: 'Who can register as a donor?',
    faq1A: 'Healthy adults aged 18-60 can register as potential donors.',
    faq2Q: 'Is kidney donation safe?',
    faq2A: 'Yes, kidney donation is generally safe for healthy individuals.',
    faq3Q: 'How does the matching process work?',
    faq3A: 'Our system matches donors and recipients based on blood type and medical factors.',
    contactTitle: 'Contact Us',
    contactDesc: 'Get in touch with our team for assistance',
    officeTitle: 'Our Office',
    officeAddress: 'Kidney Connect Sri Lanka, 123 Health Street, Colombo 05, Sri Lanka',
    contactNumbersTitle: 'Contact Numbers',
    contactNumbers: 'General Inquiries: +94 11 234 5678 | Medical Team: +94 11 234 5679 | Emergency: +94 77 123 4567',
    emailAddressesTitle: 'Email Addresses',
    emailAddresses: 'General: info@kidneyconnect.lk | Medical: medical@kidneyconnect.lk | Support: support@kidneyconnect.lk',
    officeHoursTitle: 'Office Hours',
    officeHours: 'Monday - Friday: 8:30 AM - 5:00 PM | Saturday: 9:00 AM - 1:00 PM | Sunday: Closed',
    yourName: 'Your Name',
    yourEmail: 'Your Email',
    inquiryType: 'Select Inquiry Type',
    inquiryPatient: 'Patient Registration',
    inquiryDonor: 'Donor Registration',
    inquiryTech: 'Technical Support',
    inquiryMedical: 'Medical Question',
    yourMessage: 'Your Message',
    sendMessage: 'Send Message',
    contactThanks: 'Thank you for your message! Our team will get back to you within 24 hours.',
    loggedOut: 'You have been logged out successfully.',
    passwordMismatch: 'Passwords do not match!',
    donorAgeError: 'Donors must be between 18 and 60 years old.',
    registerFailed: 'Registration failed. Please try again.',
    loginFailed: 'Login failed',
    invalidCredentials: 'Invalid login credentials.',
    provinces: {
      Western: 'Western Province',
      Central: 'Central Province',
      Southern: 'Southern Province',
      Northern: 'Northern Province',
      Eastern: 'Eastern Province',
      'North Western': 'North Western Province',
      'North Central': 'North Central Province',
      Uva: 'Uva Province',
      Sabaragamuwa: 'Sabaragamuwa Province'
    }
  },
  si: {
    nav: ['මුල් පිටුව', 'අප ගැන', 'දායකයෙකු සොයන්න', 'නිතර අසන ප්‍රශ්න', 'සම්බන්ධ වන්න'],
    quickLinks: 'ක්ෂණික සබැඳි',
    footerDesc: 'ශ්‍රී ලංකාවේ වකුගඩු රෝගීන් ගැළපෙන දායකයන් සමඟ සම්බන්ධ කරන ආරක්ෂිත, සදාචාරාත්මක සහ කාර්යක්ෂම ගැළපුම් ක්‍රමයක් හරහා කැපවූ වේදිකාවකි.',
    login: 'පුරන්න',
    register: 'ලියාපදිංචි වන්න',
    logout: 'පිටවන්න',
    welcome: 'සාදරයෙන් පිළිගනිමු',
    appName: 'Kidney Connect ශ්‍රී ලංකා',
    homeHeroTitle: 'ශ්‍රී ලංකාවේ වකුගඩු රෝගීන් හා දායකයන් අතර සම්බන්ධ කිරීම',
    homeHeroDescription: 'රෝගීන්ට ගැළපෙන වකුගඩු දායකයන් සොයා ගැනීමටත්, පුද්ගලයන්ට ජීවිත බේරා ගැනීමට දායකයන් ලෙස ලියාපදිංචි වීමටත් ආරක්ෂිත වේදිකාවකි.',
    findDonorBtn: 'දායකයෙකු සොයන්න',
    becomeDonorBtn: 'දායකයෙකු වන්න',
    langNotice: 'මෙම වේදිකාව ඉංග්‍රීසි, සිංහල සහ දෙමළ භාෂාවලින් ලබා ගත හැක. ඔබ කැමති භාෂාව ඉහතින් තෝරන්න.',
    aboutTitle: 'Kidney Connect ශ්‍රී ලංකාව ගැන',
    missionTitle: 'අපගේ අරමුණ',
    missionText: 'ශ්‍රී ලංකාවේ වකුගඩු දායකයන්ගේ තිබූ අඩුපාඩුව සම්බන්ධීකරණය කිරීම සඳහා Kidney Connect ශ්‍රී ලංකාව ස්ථාපිත කරන ලදී. ප්‍රතිස්ථාපන සඳහා රෝගීන් 1,200 කට අධික පිරිසක් බලා සිටින අතර සාමාන්‍ය රැඳී සිටීමේ කාලය වසර 4-5 ක් වන අතර, අපගේ අරමුණ ගැළපෙන දායකයන් අවශ්‍යතාවයක් ඇති රෝගීන් සමඟ සම්බන්ධ කරන ආරක්ෂිත, කාර්යක්ෂම වේදිකාවක් නිර්මාණය කිරීමයි.',
    findDonorTitle: 'ගැළපෙන දායකයෙකු සොයන්න',
    loginRequiredTitle: 'පුරන්න අවශ්‍යයි',
    loginRequired: 'දායක ගැළපුම් පද්ධතියට ප්‍රවේශ වීමට ඔබ පුරන්න අවශ්‍යයි.',
    loginNow: 'දැන් පුරන්න',
    searchCriteria: 'සෙවුම් නිර්ණායක',
    patientBloodType: 'රෝගියාගේ රුධිර වර්ගය',
    preferredDonorLocation: 'වර්ණනා කළ දායක ස්ථානය',
    anywhereSriLanka: 'ශ්‍රී ලංකාවේ ඕනෑම තැනක',
    donorAgeRange: 'දායක වයස් පරාසය',
    medicalUrgency: 'වෛද්‍ය අත්‍යවශ්‍යතාව',
    highUrgency: 'ඉහළ (දැනට ඩයලයිසිස් මත)',
    mediumUrgency: 'මධ්‍යම (ඉක්මනින් ඩයලයිසිස් අවශ්‍ය)',
    lowUrgency: 'අඩු (ප්‍රාරම්භක වකුගඩු රෝග අවධිය)',
    searchDonors: 'දායකයන් සොයන්න',
    potentialMatches: 'සම්භාව්‍ය දායක ගැළපුම්',
    matchesFoundPrefix: 'ඔබේ නිර්ණායක මත පදනම්ව, අපට හමු විය',
    matchesFoundSuffix: 'සම්භාව්‍ය දායක(යන්).',
    noMatches: 'ගැළපුම් හමු නොවීය',
    bloodType: 'රුධිර වර්ගය',
    age: 'වයස',
    location: 'ස්ථානය',
    status: 'තත්ත්වය',
    registerTitle: 'ඔබේ ගිණුම සාදන්න',
    registerDesc: 'රෝගියෙකු හෝ දායකයෙකු ලෙස ලියාපදිංචි වී අපගේ ප්‍රජාවට සම්බන්ධ වන්න',
    registerAs: 'මම ලියාපදිංචි වීමට අවශ්‍යයි:',
    patientLabel: 'රෝගියා (වකුගඩුවක් අවශ්‍යයි)',
    donorLabel: 'දායකයා (දීමනා කිරීමට අවශ්‍යයි)',
    fullName: 'සම්පූර්ණ නම',
    nicNumber: 'ජාතික හැඳුනුම්පත් අංකය',
    emailAddress: 'විද්‍යුත් තැපැල් ලිපිනය',
    phoneNumber: 'දුරකථන අංකය',
    dateOfBirth: 'උපන් දිනය',
    gender: 'ලිංගභේදය',
    selectGender: 'ලිංගභේදය තෝරන්න',
    male: 'පිරිමි',
    female: 'ගැහැණු',
    other: 'වෙනත්',
    password: 'මුරපදය',
    confirmPassword: 'මුරපදය තහවුරු කරන්න',
    selectBloodType: 'රුධිර වර්ගය තෝරන්න',
    selectProvince: 'පළාත තෝරන්න',
    agreement: 'මම නියමයන් සහ කොන්දේසිවලට එකඟ වන අතර සපයන ලද සියලුම තොරතුරු නිවැරදි බව තහවුරු කරමි.',
    createAccount: 'ගිණුම සාදන්න',
    haveAccount: 'දැනටමත් ගිණුමක් තිබේද?',
    loginHere: 'පුරන්න මෙතන',
    loginTitle: 'ඔබේ ගිණුමට පුරන්න',
    loginDesc: 'ඔබේ රෝගියා හෝ දායක පැතිකඩට ප්‍රවේශ වන්න',
    emailOrNic: 'විද්‍යුත් තැපෑල හෝ NIC',
    noAccount: 'ගිණුමක් නැද්ද?',
    registerHere: 'ලියාපදිංචි වන්න මෙතන',
    faqTitle: 'නිතර අසන ප්‍රශ්න',
    faq1Q: 'කවුරුන්ට දායකයෙකු ලෙස ලියාපදිංචි විය හැකිද?',
    faq1A: 'ශරීර සුවපත් වයස්ගත වැඩිහිටියන්ට වයස අවුරුදු 18-60 අතර දායකයන් ලෙස ලියාපදිංචි විය හැකිය.',
    faq2Q: 'වකුගඩු දීමනාව ආරක්ෂිතද?',
    faq2A: 'ඔව්, වකුගඩු දීමනාව සාමාන්‍යයෙන් සෞඛ්‍යසම්පන්න පුද්ගලයින් සඳහා ආරක්ෂිත ය.',
    faq3Q: 'ගැළපුම් ක්‍රියාවලිය ක්‍රියා කරන්නේ කෙසේද?',
    faq3A: 'අපගේ ක්‍රමය රුධිර වර්ගය සහ වෛද්‍ය සාධක මත පදනම්ව දායකයන් සහ ග්‍රාහකයන් ගැළපේ.',
    contactTitle: 'අප හා සම්බන්ධ වන්න',
    contactDesc: 'උපකාර සඳහා අපගේ කණ්ඩායම හා සම්බන්ධ වන්න',
    officeTitle: 'අපගේ කාර්යාලය',
    officeAddress: 'Kidney Connect ශ්‍රී ලංකා, 123 සෞඛ්‍ය වීදිය, කොළඹ 05, ශ්‍රී ලංකාව',
    contactNumbersTitle: 'සම්බන්ධතා අංක',
    contactNumbers: 'සාමාන්‍ය විමසීම්: +94 11 234 5678 | වෛද්‍ය කණ්ඩායම: +94 11 234 5679 | හදිසි: +94 77 123 4567',
    emailAddressesTitle: 'විද්‍යුත් තැපැල් ලිපින',
    emailAddresses: 'සාමාන්‍ය: info@kidneyconnect.lk | වෛද්‍ය: medical@kidneyconnect.lk | උපකාර: support@kidneyconnect.lk',
    officeHoursTitle: 'කාර්යාල පැය',
    officeHours: 'සඳුදා - සිකුරාදා: උදේ 8:30 - සවස 5:00 | සෙනසුරාදා: උදේ 9:00 - දවල් 1:00 | ඉරිදා: වසා ඇත',
    yourName: 'ඔබේ නම',
    yourEmail: 'ඔබේ විද්‍යුත් තැපෑල',
    inquiryType: 'විමසීම් වර්ගය තෝරන්න',
    inquiryPatient: 'රෝගියා ලියාපදිංචි කිරීම',
    inquiryDonor: 'දායකයා ලියාපදිංචි කිරීම',
    inquiryTech: 'තාක්ෂණික සහාය',
    inquiryMedical: 'වෛද්‍ය ප්‍රශ්නය',
    yourMessage: 'ඔබේ පණිවුඩය',
    sendMessage: 'පණිවුඩය යවන්න',
    contactThanks: 'ඔබේ පණිවුඩයට ස්තූතියි! අපගේ කණ්ඩායම පැය 24 ක් තුළ ඔබට පිළිතුරු දෙනු ඇත.',
    loggedOut: 'ඔබ සාර්ථකව පිටව ඇත.',
    passwordMismatch: 'මුරපද ගැලපෙන්නේ නැත!',
    donorAgeError: 'දායකයන් වයස අවුරුදු 18 සහ 60 අතර විය යුතුය.',
    registerFailed: 'ලියාපදිංචිය අසාර්ථක විය. කරුණාකර නැවත උත්සාහ කරන්න.',
    loginFailed: 'පුරන්න අසාර්ථක විය',
    invalidCredentials: 'වලංගු නොවන පිවිසුම් අක්තපත්ර.',
    provinces: {
      Western: 'බස්නාහිර පළාත',
      Central: 'මධ්‍යම පළාත',
      Southern: 'දකුණු පළාත',
      Northern: 'උතුරු පළාත',
      Eastern: 'නැගෙනහිර පළාත',
      'North Western': 'වයඹ පළාත',
      'North Central': 'උතුරු මැද පළාත',
      Uva: 'ඌව පළාත',
      Sabaragamuwa: 'සබරගමුව පළාත'
    }
  },
  ta: {
    nav: ['முகப்பு', 'எங்களைப் பற்றி', 'நன்கொடையாளரைக் கண்டறியவும்', 'அடிக்கடி கேட்கப்படும் கேள்விகள்', 'தொடர்புக்கு'],
    quickLinks: 'விரைவு இணைப்புகள்',
    footerDesc: 'இலங்கையில் சிறுநீரக நோயாளிகள் பொருந்தக்கூடிய நன்கொடையாளர்களுடன் பாதுகாப்பான, நெறிமுறை மற்றும் திறமையான பொருத்தம் அமைப்பு மூலம் இணைக்கப்படும் ஒரு தளமாகும்.',
    login: 'உள்நுழைய',
    register: 'பதிவு செய்',
    logout: 'வெளியேறு',
    welcome: 'வரவேற்கிறோம்',
    appName: 'Kidney Connect இலங்கை',
    homeHeroTitle: 'இலங்கையில் சிறுநீரக நோயாளிகள் மற்றும் தாராள மனப்பான்மையுள்ள நன்கொடையாளர்களை இணைத்தல்',
    homeHeroDescription: 'நோயாளிகள் பொருந்தக்கூடிய சிறுநீரக நன்கொடையாளர்களைக் கண்டறியவும், தனிநபர்கள் உயிர்களைக் காப்பாற்ற சாத்தியமான நன்கொடையாளர்களாகப் பதிவு செய்யவும் பாதுகாப்பான தளமாகும்.',
    findDonorBtn: 'நன்கொடையாளரைக் கண்டறியவும்',
    becomeDonorBtn: 'நன்கொடையாளராகுங்கள்',
    langNotice: 'இந்த தளம் ஆங்கிலம், சிங்களம் மற்றும் தமிழ் மொழிகளில் கிடைக்கிறது. உங்கள் விருப்ப மொழியை மேலே தேர்ந்தெடுக்கவும்.',
    aboutTitle: 'Kidney Connect இலங்கை பற்றி',
    missionTitle: 'எங்கள் நோக்கம்',
    missionText: 'இலங்கையில் சிறுநீரக நன்கொடையாளர்களின் முக்கிய பற்றாக்குறையை சமாளிக்க Kidney Connect இலங்கை நிறுவப்பட்டது. 1,200 க்கும் மேற்பட்ட நோயாளிகள் மாற்று அறுவை சிகிச்சைக்காகக் காத்திருக்கும் நிலையில், சராசரி காத்திருப்பு நேரம் 4-5 ஆண்டுகள் என்பதால், பொருந்தக்கூடிய நன்கொடையாளர்களைத் தேவையுள்ள நோயாளிகளுடன் இணைக்கும் பாதுகாப்பான, திறமையான தளத்தை உருவாக்குவதே எங்கள் நோக்கமாகும்.',
    findDonorTitle: 'பொருந்தக்கூடிய நன்கொடையாளரைக் கண்டறியவும்',
    loginRequiredTitle: 'உள்நுழைவு தேவை',
    loginRequired: 'நன்கொடையாளர் பொருத்தம் அமைப்பை அணுக உங்கள் கணக்கில் உள்நுழைய வேண்டும்.',
    loginNow: 'இப்போது உள்நுழைய',
    searchCriteria: 'தேடல் அளவுகோல்கள்',
    patientBloodType: 'நோயாளியின் ரத்த வகை',
    preferredDonorLocation: 'விருப்பமான நன்கொடையாளர் இடம்',
    anywhereSriLanka: 'இலங்கையில் எங்கும்',
    donorAgeRange: 'நன்கொடையாளர் வயது வரம்பு',
    medicalUrgency: 'மருத்துவ அவசரத்தன்மை',
    highUrgency: 'உயர் (தற்போது டயாலிசிஸில்)',
    mediumUrgency: 'நடுத்தரம் (விரைவில் டயாலிசிஸ் தேவை)',
    lowUrgency: 'குறைவு (ஆரம்ப சிறுநீரக நோய்)',
    searchDonors: 'நன்கொடையாளர்களைத் தேடுங்கள்',
    potentialMatches: 'சாத்தியமான நன்கொடையாளர் பொருத்தங்கள்',
    matchesFoundPrefix: 'உங்கள் அளவுகோல்களின் அடிப்படையில், எங்களுக்கு கிடைத்தது',
    matchesFoundSuffix: 'சாத்தியமான நன்கொடையாளர்(கள்).',
    noMatches: 'பொருத்தங்கள் கிடைக்கவில்லை',
    bloodType: 'ரத்த வகை',
    age: 'வயது',
    location: 'இடம்',
    status: 'நிலை',
    registerTitle: 'உங்கள் கணக்கை உருவாக்கவும்',
    registerDesc: 'நோயாளி அல்லது நன்கொடையாளராகப் பதிவு செய்து எங்கள் சமூகத்தில் சேரவும்',
    registerAs: 'நான் பதிவு செய்ய விரும்புகிறேன்:',
    patientLabel: 'நோயாளி (சிறுநீரகம் தேவை)',
    donorLabel: 'நன்கொடையாளர் (நன்கொடை வழங்க விரும்புகிறேன்)',
    fullName: 'முழுப் பெயர்',
    nicNumber: 'தேசிய அடையாள அட்டை எண்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    phoneNumber: 'தொலைபேசி எண்',
    dateOfBirth: 'பிறந்த தேதி',
    gender: 'பாலினம்',
    selectGender: 'பாலினத்தைத் தேர்ந்தெடுக்கவும்',
    male: 'ஆண்',
    female: 'பெண்',
    other: 'மற்றவை',
    password: 'கடவுச்சொல்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    selectBloodType: 'ரத்த வகையைத் தேர்ந்தெடுக்கவும்',
    selectProvince: 'மாகாணத்தைத் தேர்ந்தெடுக்கவும்',
    agreement: 'விதிமுறைகள் மற்றும் நிபந்தனைகளை நான் ஒப்புக்கொள்கிறேன் மற்றும் வழங்கப்பட்ட அனைத்துத் தகவல்களும் துல்லியமானவை என உறுதிப்படுத்துகிறேன்.',
    createAccount: 'கணக்கை உருவாக்கவும்',
    haveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    loginHere: 'உள்நுழைய இங்கே',
    loginTitle: 'உங்கள் கணக்கில் உள்நுழையவும்',
    loginDesc: 'உங்கள் நோயாளி அல்லது நன்கொடையாளர் சுயவிவரத்தை அணுகவும்',
    emailOrNic: 'மின்னஞ்சல் அல்லது NIC',
    noAccount: 'கணக்கு இல்லையா?',
    registerHere: 'பதிவு செய்ய இங்கே',
    faqTitle: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    faq1Q: 'யார் நன்கொடையாளராகப் பதிவு செய்யலாம்?',
    faq1A: 'ஆரோக்கியமான பெரியவர்கள் 18-60 வயதுக்குட்பட்டவர்கள் சாத்தியமான நன்கொடையாளர்களாகப் பதிவு செய்யலாம்.',
    faq2Q: 'சிறுநீரக நன்கொடை பாதுகாப்பானதா?',
    faq2A: 'ஆம், சிறுநீரக நன்கொடை பொதுவாக ஆரோக்கியமான நபர்களுக்கு பாதுகாப்பானது.',
    faq3Q: 'பொருத்தம் செய்யும் செயல்முறை எவ்வாறு செயல்படுகிறது?',
    faq3A: 'எங்கள் அமைப்பு ரத்த வகை மற்றும் மருத்துவ காரணிகளின் அடிப்படையில் நன்கொடையாளர்கள் மற்றும் பெறுநர்களை பொருத்துகிறது.',
    contactTitle: 'எங்களை தொடர்பு கொள்ளவும்',
    contactDesc: 'உதவிக்கு எங்கள் குழுவைத் தொடர்பு கொள்ளவும்',
    officeTitle: 'எங்கள் அலுவலகம்',
    officeAddress: 'Kidney Connect இலங்கை, 123 சுகாதார தெரு, கொழும்பு 05, இலங்கை',
    contactNumbersTitle: 'தொடர்பு எண்கள்',
    contactNumbers: 'பொது விசாரணைகள்: +94 11 234 5678 | மருத்துவ குழு: +94 11 234 5679 | அவசர: +94 77 123 4567',
    emailAddressesTitle: 'மின்னஞ்சல் முகவரிகள்',
    emailAddresses: 'பொது: info@kidneyconnect.lk | மருத்துவ: medical@kidneyconnect.lk | ஆதரவு: support@kidneyconnect.lk',
    officeHoursTitle: 'அலுவலக நேரங்கள்',
    officeHours: 'திங்கள் - வெள்ளி: காலை 8:30 - மாலை 5:00 | சனி: காலை 9:00 - மதியம் 1:00 | ஞாயிறு: மூடப்பட்டது',
    yourName: 'உங்கள் பெயர்',
    yourEmail: 'உங்கள் மின்னஞ்சல்',
    inquiryType: 'விசாரணை வகையைத் தேர்ந்தெடுக்கவும்',
    inquiryPatient: 'நோயாளி பதிவு',
    inquiryDonor: 'நன்கொடையாளர் பதிவு',
    inquiryTech: 'தொழில்நுட்ப ஆதரவு',
    inquiryMedical: 'மருத்துவ கேள்வி',
    yourMessage: 'உங்கள் செய்தி',
    sendMessage: 'செய்தியை அனுப்பவும்',
    contactThanks: 'உங்கள் செய்திக்கு நன்றி! எங்கள் குழு 24 மணி நேரத்திற்குள் உங்களுக்கு பதிலளிக்கும்.',
    loggedOut: 'நீங்கள் வெற்றிகரமாக வெளியேறியுள்ளீர்கள்.',
    passwordMismatch: 'கடவுச்சொற்கள் பொருந்தவில்லை!',
    donorAgeError: 'நன்கொடையாளர்களின் வயது 18 முதல் 60 வரை இருக்க வேண்டும்.',
    registerFailed: 'பதிவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.',
    loginFailed: 'உள்நுழைவு தோல்வியடைந்தது',
    invalidCredentials: 'தவறான உள்நுழைவு சான்றுகள்.',
    provinces: {
      Western: 'மேற்கு மாகாணம்',
      Central: 'மத்திய மாகாணம்',
      Southern: 'தெற்கு மாகாணம்',
      Northern: 'வடக்கு மாகாணம்',
      Eastern: 'கிழக்கு மாகாணம்',
      'North Western': 'வடமேற்கு மாகாணம்',
      'North Central': 'வடமத்திய மாகாணம்',
      Uva: 'ஊவா மாகாணம்',
      Sabaragamuwa: 'சபராகமுவா மாகாணம்'
    }
  }
};

export const provinces = ['Western', 'Central', 'Southern', 'Northern', 'Eastern', 'North Western', 'North Central', 'Uva', 'Sabaragamuwa'];
